name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  gh-pages-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
      env: { CI: true }
    - run: yarn build
      env: { CI: true }
    - name: Set up SSH keys
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_ed25519
        chmod go-rwx ~/.ssh/id_ed25519
        ssh -i ~/.ssh/id_ed25519 git@github.com
    - name: Upload to gh-pages
      env:
        CI: true
        GIT_SSH_COMMAND: ssh -i ~/.ssh/id_ed25519
      run:
        "yarn deploy -u 'Hack Bot <uclaacmhack+ghbot@gmail.com>' \
                     -r 'git@github.com:uclaacm/hack.uclaacm.com.git'"
